Query:
  type: object
  config:
    description: "Query"
    fields:
      environments:
        type: "[Environments]"
        resolve: "@=resolver('Environments')"
      environment:
        type: "Environments"
        args:
          id:
            description: "Get by ID"
            type: "Int"
        resolve: "@=resolver('Environment',[args])"
      configmaps:
        type: "[ConfigMap]"
        resolve: "@=resolver('ConfigMaps')"
